openapi: 3.0.0
info:
  title: Authentication API
  version: 1.0.0
paths:
  /auth/me:
    get:
      summary: Get current authenticated user details
      responses:
        '200':
          description: Current user details
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                    format: uuid
                  email:
                    type: string
                    format: email
        '401':
          description: Unauthorized
