openapi: 3.0.0
info:
  title: Authentication API
  version: 1.0.0
paths:
  /auth/login:
    post:
      summary: Authenticate a user and return a session token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                password:
                  type: string
                  format: password
                  description: User's password
      responses:
        '200':
          description: User successfully authenticated
          headers:
            Set-Cookie:
              schema:
                type: string
                example: "session_id=abcde12345; HttpOnly; Path=/; Max-Age=3600"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Login successful
        '401':
          description: Invalid credentials
