openapi: 3.0.0
info:
  title: User Profile API
  version: 1.0.0
paths:
  /profile:
    get:
      summary: Retrieve the authenticated user's profile
      responses:
        '200':
          description: User profile data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '401':
          description: Unauthorized
        '404':
          description: Profile not found
    post:
      summary: Create or update the authenticated user's profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserProfileUpdate'
      responses:
        '200':
          description: Profile successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '201':
          description: Profile successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
components:
  schemas:
    UserProfile:
      type: object
      properties:
        userId:
          type: string
          format: uuid
          readOnly: true
        age_range:
          type: string
          enum: ['under_18', '18_24', '25_34', '35_plus']
        education_level:
          type: string
          enum: ['high_school', 'undergrad', 'masters', 'phd', 'self_taught']
        tech_background:
          type: string
          enum: ['software_engineer', 'hardware_engineer', 'student', 'hobbyist']
        primary_goal:
          type: string
          enum: ['career_switch', 'academic', 'hobby_project', 'startup_founder']
        learning_mode:
          type: string
          enum: ['visual', 'textual', 'code_first']
        learning_speed:
          type: string
          enum: ['intensive', 'balanced', 'casual']
        time_per_week:
          type: integer
          minimum: 0
        preferred_language:
          type: string
          default: 'en'
    UserProfileUpdate:
      type: object
      properties:
        age_range:
          type: string
          enum: ['under_18', '18_24', '25_34', '35_plus']
        education_level:
          type: string
          enum: ['high_school', 'undergrad', 'masters', 'phd', 'self_taught']
        tech_background:
          type: string
          enum: ['software_engineer', 'hardware_engineer', 'student', 'hobbyist']
        primary_goal:
          type: string
          enum: ['career_switch', 'academic', 'hobby_project', 'startup_founder']
        learning_mode:
          type: string
          enum: ['visual', 'textual', 'code_first']
        learning_speed:
          type: string
          enum: ['intensive', 'balanced', 'casual']
        time_per_week:
          type: integer
          minimum: 0
        preferred_language:
          type: string
          default: 'en'